import groovy.json.JsonSlurperClassic

def jsonParse(def json) {
    new groovy.json.JsonSlurperClassic().parseText(json)
}
pipeline {
  //agent { label 'master' }
  agent any
  environment {
    appName = "variable" 
  }
  stages {

 stage("paso 1"){
     
      steps {
          script {			
           //sh "echo 'hola mundo'"
           echo "Hello World!"
        }
      }
    }
  }
  post {
      always {          
          deleteDir()
           //sh "echo 'fase always'"
           echo "fase always"
      }
      success {
            //sh "echo 'fase success'"
            echo "fase success"
        }

      failure {
            //sh "echo 'fase failure'"
            echo "fase failure"
      }
      
  }
}  

